name: gerenciador_de_projetos
description: "Um gerenciador de projetos de arquitetura."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gestão de Estado
  provider: ^6.1.2

  # Banco de Dados Local (Drift)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.9.0

  # Utilitários
  uuid: ^4.3.3

  # Desktop
  window_manager: ^0.3.8

  # Ícones (Padrão)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de Código (Drift)
  drift_dev: ^2.14.1
  build_runner: ^2.4.8

  # Análise de Código
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Declaração dos assets do projeto
  assets:
    - assets/project_template.json