// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkV540bxDFqKWlRtDZGegNp-CNt40rEww',
    appId: '1:790272578055:web:b3e03ac7e793384ea750a2',
    messagingSenderId: '790272578055',
    projectId: 'gerenciamento-de-projeto-f2697',
    authDomain: 'gerenciamento-de-projeto-f2697.firebaseapp.com',
    storageBucket: 'gerenciamento-de-projeto-f2697.firebasestorage.app',
    measurementId: 'G-B0C3HJ4JEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmaNGU9mSnp3I5JhalVi_gHEiVfLjS0W8',
    appId: '1:790272578055:android:372d4113e9c50992a750a2',
    messagingSenderId: '790272578055',
    projectId: 'gerenciamento-de-projeto-f2697',
    storageBucket: 'gerenciamento-de-projeto-f2697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp6AQ_qC2js9YUPNYEoW2SzbXs2rTT2Lg',
    appId: '1:790272578055:ios:6fbf4d68f77464f0a750a2',
    messagingSenderId: '790272578055',
    projectId: 'gerenciamento-de-projeto-f2697',
    storageBucket: 'gerenciamento-de-projeto-f2697.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorDeProjetos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp6AQ_qC2js9YUPNYEoW2SzbXs2rTT2Lg',
    appId: '1:790272578055:ios:6fbf4d68f77464f0a750a2',
    messagingSenderId: '790272578055',
    projectId: 'gerenciamento-de-projeto-f2697',
    storageBucket: 'gerenciamento-de-projeto-f2697.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorDeProjetos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkV540bxDFqKWlRtDZGegNp-CNt40rEww',
    appId: '1:790272578055:web:f487f14947276e70a750a2',
    messagingSenderId: '790272578055',
    projectId: 'gerenciamento-de-projeto-f2697',
    authDomain: 'gerenciamento-de-projeto-f2697.firebaseapp.com',
    storageBucket: 'gerenciamento-de-projeto-f2697.firebasestorage.app',
    measurementId: 'G-VYZ9B9RQFD',
  );
}
