name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # 1. INSTALA O FLUTTER NA MÁQUINA VIRTUAL
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 2. BAIXA AS DEPENDÊNCIAS DO SEU PROJETO (pubspec.yaml)
      - run: flutter pub get
      
      # 3. INJETA AS CHAVES DE PRODUÇÃO
      - name: Inject Firebase Options
        run: echo "${{ secrets.FIREBASE_OPTIONS_PROD }}" > lib/firebase_options.dart
        
      # 4. COMPILA PARA WEB
      - run: flutter build web
      
      # 5. FAZ O DEPLOY NO FIREBASE
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GERENCIAMENTO_DE_PROJETO_F2697 }}
          channelId: live
          projectId: gerenciamento-de-projeto-f2697